// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlfkrpytemlejkjzvxtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsZmtycHl0ZW1sZWpranp2eHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzA4NDQsImV4cCI6MjA2NDI0Njg0NH0.MokH53zEqhG7YtqV0AJa73mPUAoILTZE9HKxNlGs9Nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);